# -*- coding: utf-8 -*-
"""helloworld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c721zcM8y4f70xPlgvXzWJo1BMG2JiWf
"""

print("hello")